FROM {{BASE_IMAGE}} AS build

WORKDIR /app

COPY package*.json ./
RUN {{INSTALL_CMD}}

COPY . .
RUN {{BUILD_CMD}}

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
